
import type { Metadata } from "next";
import localFont from 'next/font/local'; 
import { Toaster } from "sonner";
import "./globals.css";
import CustomNav from "@/components/CutomNav";  
import { Providers } from "./provider";

const popppins = localFont({
  display: 'swap',
  src: [
    {
      path: '../public/fonts/poppins.woff2',
    },
  ],
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: "feedback-collector",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;   

}>) { 
  
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body 
      suppressHydrationWarning={true}
        className={`${popppins.variable} antialiased  `}
      > 
      <Providers>
       <CustomNav/>
        {children} 
          <Toaster/> 
         </Providers>
      </body>
    </html>
  );
}
