import type { Metadata } from "next";
import localFont from 'next/font/local'; 
import { Toaster } from "sonner";
import "./globals.css";
import Nav from "@/components/LandingPageComp/Nav"; 

const popppins = localFont({
  display: 'swap',
  src: [
    {
      path: '../public/fonts/poppins.woff2',
    },
  ],
  variable: '--font-poppins',
});


export const metadata: Metadata = {
  title: "feedback-collector",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body 
      suppressHydrationWarning={true}
        className={`${popppins.variable} antialiased`}
      > 
         <Nav /> 
        {children} 
          <Toaster/>
      </body>
    </html>
  );
}
